sudo: required
services:
  - docker
language: python
python:
  - "3.5"

install:
  - pip install codecov tox

script:
  - tox -e py35
  - docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c "export LC_ALL=en_US.UTF-8 && locale-gen en_US.UTF-8 && sed -i s/archive.ubuntu.com/us.archive.ubuntu.com/g /etc/apt/sources.list && apt-get update && apt-get install -y snapcraft git && cd $(pwd) && snapcraft"

after_success:
  - codecov --env TRAVIS_PYTHON_VERSION

branches:
  only:
    - master
