name: meta-maas
version: 0.2
summary: Tool to manage multiple MAAS regions
description: Tool to manage multiple MAAS regions
grade: stable
confinement: strict

apps:
  meta-maas:
    command: bin/meta-maas
    plugs:
      - home
      - network-bind

parts:
  meta-maas:
    plugin: python
    source: .
    requirements: requirements.txt
  meta-html:
    plugin: gulp
    source: .
    gulp-tasks:
      - default
      - snap-install
    organize:
      assets: lib/python3.5/site-packages/meta_maas/html/assets
      libs: lib/python3.5/site-packages/meta_maas/html/libs
